<a href="https://colab.research.google.com/github/Antara80978/Matrix-operations-in-Numpy/blob/main/task14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#Create a matrix

A = np.array([[1 , 2, 3],
              [4, 5, 6 ],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

In [3]:

# Display matrices
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [4]:
# Matrix addition
addition = A + B
print("\nMatrix Addition:")
print(addition)


Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [5]:
# Matrix subtraction
subtraction = A - B
print("\nMatrix Subtraction:")
print(subtraction)


Matrix Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [6]:
# Matrix multiplication
multiplication = A @ B
print("\nMatrix Multiplication:")
print(multiplication)


Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [7]:

# Transpose of matrices
transpose_A = A.T
transpose_B = B.T

In [8]:
print("\nTranspose of Matrix A:")
print(transpose_A)


Transpose of Matrix A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [9]:
print("\nTranspose of Matrix B:")
print(transpose_B)


Transpose of Matrix B:
[[9 6 3]
 [8 5 2]
 [7 4 1]]
